### ISSUE TITLE
Servers need authentication

### ISSUE THREAD

**Issue by MarmeladeTheCat** [zardoy/minecraft-web-client#36]
Whenever I try to open a server, I get the error message “You have been disconnected from the server. End reason: this server appears to be an online server and you are providing no authentication. Try authenticating first.” Last status: Connecting to server

Is there any way to resolve this? I am using working proxies and ports.

**Comment by zardoy** [comment]
Hi! For now only Java servers running in offline mode are supported. Otherwise you need to provide Microsoft account credentials for authentication which is not supported by the proxy at the moment. This is not hard to support so I might add it in the near future.

If you own the server you can change online mode to false in [server.properties](https://minecraft.fandom.com/wiki/Server.properties). Or the server is not running in online mode? Please let me know 🙏

**Comment by TapsHTS** [comment]
Any news about an auth system ? Or it is possible to explain how to enable auth when we clone the repo ?

**Comment by zardoy** [comment]
> Any news about an auth system ? Or it is possible to explain how to enable auth when we clone the repo ?

I abandoned development of that system because:

1. This can't be 100% safe. MC auth system doesn't support cors so its not possible to obtain the token on the client side (right in your browser). You have to send either send login/password, or (most likely) use oauth2 auth process provided by the server. In this case you will need to login/click continue in the popup window each time you want to connect to the server from the web.
2. MS bans our server when we do the full auth pipeline for some reason. You can look into prismarineJSnode-minecraft-protocol/issues/372 to better understand the issue. I can find a solution for this but it will require more time.

> Or it is possible to explain how to enable auth when we clone the repo ?

There are no features that are available only if you clone this locally. This feature is not implemented yet and there is no simple toggle. However, implementing simple auth in the proxy code can be relatively simple.

**Comment by zardoy** [comment]
I have updated the connect screen to support more options with the new proxy selector, so this feature is really close!

**Comment by zardoy** [comment]
available now on s.mcraft.fun . Current status: supports only vanilla servers above 1.19.4 (tested on 1.20.2).
There is still a lot of work towards hypixel support
